### ISSUE TITLE
Mj-TemplateLanguage

### ISSUE THREAD

**Issue by movingwater** [bnomei/kirby3-mailjet#3]
Hi bnomei
Just messed around with this plugin. Looks very promising. THanks alot.
What I didn't get ist how I can send E-Mail with template variables.
You mention in "examples/email.php" how to send with the kirby mailer. But as far I have seen that mailer doesn't support custom headers. Or how can I add this header:
> In order to have the template language interpreted through the SMTP relay, you must provide X-Mj-TemplateLanguage header and set it to true.

(from: https://dev.mailjet.com/email/template-language/SMTP/)

Or how can I get mj's template language to work?

**Comment by bnomei** [comment]
its not possible right now (with out a hack). i created idea issue.
https://github.com/getkirby/ideas/issues/541

about the hack... just add the lines here and do NOT update kirby or apply hack again if you do.
https://github.com/getkirby/kirby/blob/6bd14bc8099d6c9dbe67ef0582b8c0a2d4c0888c/src/Email/PHPMailer.php#L70

```php
$mailer->addCustomHeader('X-MJ-TemplateID', $yourTemplateID);
$mailer->addCustomHeader('X-MJ-TemplateLanguage', true);
// X-MJ-TemplateErrorReporting
// X-MJ-TemplateErrorDeliver
// X-MJ-Vars
```

> TIP: if you use composer you can create a composer skript to 'patch' the file in the vendor folder using basic bash commands like [sed](https://www.cyberciti.biz/faq/how-to-use-sed-to-find-and-replace-text-in-files-in-linux-unix-shell/).

**Comment by bnomei** [comment]
## my current templating solution
i am using handlebars/mustache inside my mjml (with mj-raw) to create a template. then i do parse that with data from kirby and send it. given i can not use mailjets passport with that technique. but i can dump the result as a website to generate a preview.

**example.mjml (with handlebars)***
```xml
<mj-body background-color="#fff">
    <mj-include path="./spacer-white.mjml" />
    <mj-include path="./logo-title.mjml" />
    
    <mj-raw>{{# blocks }}</mj-raw>
   
      <mj-raw>{{#if image }}</mj-raw>
    		<mj-include path="./block-image.mjml" />
    	<mj-raw>{{/if }}</mj-raw>
   
      <mj-raw>{{#if isexcerpt }}</mj-raw>
    		<mj-include path="./block-excerpt.mjml" />
    	<mj-raw>{{/if }}</mj-raw>

  	<mj-raw>{{/blocks }}</mj-raw>

    <mj-include path="./copyright.mjml" />
    <mj-include path="./address.mjml" />
</mj-body>
```

**block-excerpt.mjml**
```xml
<mj-section mj-class="section-borders" padding="0px 12px 24px">
  <mj-group>
    <mj-column padding="0px">
      <mj-raw>{{#if datedesc }}</mj-raw>
      <mj-text mj-class="h4" padding-top="4px" padding-bottom="4px">
        <mj-raw>{{ datedesc }}</mj-raw>
      </mj-text>
      <mj-raw>{{/if }}</mj-raw>
      
      <mj-raw>{{#if title }}</mj-raw>
      <mj-text mj-class="h2">
        <mj-raw>{{ title }}</mj-raw>
      </mj-text>
      <mj-raw>{{/if }}</mj-raw>
      
      <mj-raw>{{#if subtitle }}</mj-raw>
      <mj-text mj-class="h3">
        <mj-raw>{{ subtitle }}</mj-raw>
      </mj-text>
      <mj-raw>{{/if }}</mj-raw>
      
      <mj-raw>{{#if text }}</mj-raw>
      <mj-text mj-class="p">
        <mj-raw>{{ text }}</mj-raw>
      </mj-text>
      <mj-raw>{{/if }}</mj-raw>
      
      <mj-raw>{{#if location }}</mj-raw>
      <mj-text mj-class="h5" padding-top="4px" padding-bottom="4px">
        <mj-raw>{{ location }}</mj-raw>
      </mj-text>
      <mj-raw>{{/if }}</mj-raw>
    </mj-column>
  </mj-group>
</mj-section>
```

or shorter for simple text but mj-raw is still needed when you want to wrap mjml elements.
```xml
      <mj-text mj-class="p">{{#if text }}{{ text }}{{/if }}</mj-text>
```

this generates a the html which i save as `*.hbs` and parse with [handlebars](https://github.com/bnomei/kirby3-handlebars) (you do not have to use that [plugin for templates](https://github.com/bnomei/kirby3-handlebars/wiki/Setup:-Template-Component), just as a parser will do). you need to set `bnomei.handlebars.component => false`.

```php
$dataArray = [
    'blocks' = [
         [
              'image' => null,
              'isexcerpt' => true,
              'text' => 'TEXT',
         ],
         // more "blocks"
    ],
    // other vars
];
// site/templates/example.hbs => the html from example.mjml
$html = \handlebars('example', $dataArray, true); // true = return not echo.
```

> ATTENTION: hbs plugin can only load templates from site/templates not subfolders.

**Comment by bnomei** [comment]
@movingwater see

https://github.com/getkirby/ideas/issues/541#issuecomment-672267928
